//GET http://localhost:3003/api/blogs
//GET http://localhost:3003/api/users

POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "testikayttaja",
    "name": "Testi Käyttäjä",
    "password": "supersalainen"
}