POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
  "username": "kayttaja1",
  "name": "Tämän käyttäjän salasana on salasana",
  "password": "salasana"
}

###


POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
  "username": "kayttaja1",
  "password": "salasana"
}

###


POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
  "username": "toka",
  "password": "salainenstring"
}


###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRva2EiLCJpZCI6IjYzYzY5NGM3ZDJmYjQ5ZTFiZWM5YmNiZCIsImlhdCI6MTY3NDgzNzA3MCwiZXhwIjoxNjc0ODQwNjcwfQ.woVcN61GG17XmV6FIKoubeclfQXLzMOrH-UTxlO2ks8

{
    "title": "Blog about tokens",
    "author": "Cappuchichino",
    "url": "www.tokens101.com",
    "likes": 1
}